### ISSUE TITLE
alexa_info.json

### ISSUE THREAD

**Issue by Zavy86** [mscalora/suzie-skill#1]
hi, i'm trying your endpoint source code, were i can find this file?

**Comment by mscalora** [comment]
This is very old, have not used it in years.

I believe you have to get your own info with your own amazon account, it
should look like this:

*{*


*  "appId": "amzn1.ask.skill.XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX",
"userId":
"amzn1.ask.account.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}*

**Comment by Zavy86** [comment]
Ah ok thanks! work!
